# Generated by Django 3.2.12 on 2022-02-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('District Admin', 'District Admin'), ('Primary Nurse', 'Primary Nurse'), ('Secondary Nurse', 'Secondary Nurse')], default='District Admin', max_length=20),
        ),
    ]
