# Generated by Django 3.2.12 on 2022-03-01 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_last_sent',
            field=models.DateField(default=datetime.date(2022, 3, 1)),
        ),
        migrations.AddField(
            model_name='user',
            name='email_preff_time',
            field=models.TimeField(default=datetime.time(17, 50, 0, 284212)),
        ),
    ]
