# Generated by Django 3.2.12 on 2022-03-02 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220301_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_last_sent',
            field=models.DateField(default=datetime.date(2022, 3, 2)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_preff_time',
            field=models.TimeField(default=datetime.time(22, 50, 27, 424155)),
        ),
    ]
