# Generated by Django 3.2.12 on 2022-02-25 17:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icds_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('expired_time', models.DateField()),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('emergency_phone_number', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('care_type', models.CharField(max_length=20)),
                ('care_sub_type', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 2, 25, 22, 38, 12, 384470))),
                ('duration', models.IntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('sugar', models.FloatField()),
                ('mouth_hygiene', models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('ok', 'Ok')], max_length=4)),
                ('public_hygiene', models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('ok', 'Ok')], max_length=4)),
                ('systemic_examination', models.TextField()),
                ('patient_at_peace', models.BooleanField()),
                ('pain', models.BooleanField()),
                ('symptoms', models.CharField(choices=[('fever', 'Fever'), ('caughing', 'Caughing')], max_length=20)),
                ('note', models.TextField()),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.visitschedule')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('description', models.TextField()),
                ('care_type', models.CharField(max_length=10)),
                ('care_sub_type', models.CharField(max_length=20)),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('relation', models.CharField(choices=[('S', 'Sister'), ('B', 'Brother'), ('F', 'Father'), ('M', 'Mother')], max_length=1)),
                ('address', models.TextField()),
                ('education', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=10)),
                ('remarks', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
