# Generated by Django 3.2.12 on 2022-02-25 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitschedule',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 1, 9, 5, 432869)),
        ),
    ]
