# Generated by Django 3.2.12 on 2022-02-27 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_visitschedule_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitschedule',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 12, 14, 31, 372922)),
        ),
    ]
