# Generated by Django 3.2.12 on 2022-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20220227_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitschedule',
            name='datetime',
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
