# Generated by Django 3.2.12 on 2022-03-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20220228_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitschedule',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='visitschedule',
            name='patient',
        ),
        migrations.DeleteModel(
            name='VisitDetails',
        ),
        migrations.DeleteModel(
            name='VisitSchedule',
        ),
    ]
