# Generated by Django 3.2.12 on 2022-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20220301_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
