# Generated by Django 3.2.12 on 2022-03-04 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20220304_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 34598, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 33356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 31913, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 35402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 36403, tzinfo=utc)),
        ),
    ]
