# Generated by Django 3.2.12 on 2022-03-12 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20220304_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 778296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 777857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 777382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 778569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 778881, tzinfo=utc)),
        ),
    ]
