# Generated by Django 3.2.12 on 2022-03-01 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0007_auto_20220301_1307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('duration', models.IntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('sugar', models.FloatField()),
                ('mouth_hygiene', models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('ok', 'Ok')], max_length=4)),
                ('public_hygiene', models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('ok', 'Ok')], max_length=4)),
                ('systemic_examination', models.TextField()),
                ('patient_at_peace', models.BooleanField()),
                ('pain', models.BooleanField()),
                ('symptoms', models.CharField(choices=[('fever', 'Fever'), ('caughing', 'Caughing')], max_length=20)),
                ('note', models.TextField()),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.visitschedule')),
            ],
        ),
    ]
