# Generated by Django 3.2.12 on 2022-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdetails',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
