# Generated by Django 3.2.12 on 2022-03-03 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20220303_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 48, 47, 169824, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='visitdetails',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 48, 47, 168409, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
