# Generated by Django 3.2.12 on 2022-03-04 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20220304_2225'),
        ('visits', '0003_auto_20220304_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 55, 25, 326383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 55, 25, 325126, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 55, 25, 327597, tzinfo=utc))),
                ('updated_at', models.DateTimeField(null=True)),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.treatment')),
            ],
        ),
    ]
