# Generated by Django 3.2.12 on 2022-03-04 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20220304_2228'),
        ('visits', '0004_auto_20220304_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentnote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 58, 46, 500162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='treatmentnote',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.treatment'),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 58, 46, 499184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 58, 46, 498165, tzinfo=utc)),
        ),
    ]
