# Generated by Django 3.2.12 on 2022-03-04 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20220304_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentnote',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visitschedule'),
        ),
        migrations.AlterField(
            model_name='treatmentnote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 40984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 39722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 38487, tzinfo=utc)),
        ),
    ]
