# Generated by Django 3.2.12 on 2022-03-12 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_auto_20220304_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentnote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 780550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 780052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 13, 42, 45, 779619, tzinfo=utc)),
        ),
    ]
