# Generated by Django 3.2.12 on 2022-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
