# Generated by Django 3.2.12 on 2022-03-03 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_auto_20220303_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbody',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 48, 47, 153057, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='localbody',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 48, 47, 154003, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ward',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 48, 47, 154979, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 48, 47, 151271, tzinfo=utc)),
        ),
    ]
