# Generated by Django 3.2.12 on 2022-03-04 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_auto_20220304_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 55, 25, 313164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='localbody',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 55, 25, 311402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 55, 25, 309791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 55, 25, 312267, tzinfo=utc)),
        ),
    ]
