# Generated by Django 3.2.12 on 2022-03-04 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_auto_20220304_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 58, 46, 487929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='localbody',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 58, 46, 486269, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 58, 46, 484659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 58, 46, 487098, tzinfo=utc)),
        ),
    ]
