# Generated by Django 3.2.12 on 2022-03-04 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_auto_20220304_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 26093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='localbody',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 24370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 22635, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 17, 7, 46, 25195, tzinfo=utc)),
        ),
    ]
